# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 04:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 9, 22, 4, 11, 28, 281831, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
